# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\VScode__projects\课设\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from src.lib.DataBaseFunc import getRankingList
from src.classes.GameRecord import GameRecord
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QScrollArea, QApplication, QWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Rank")
        MainWindow.setEnabled(False)
        MainWindow.resize(700, 530)

        MainWindow.setMinimumSize(QtCore.QSize(750, 530))
        MainWindow.setMaximumSize(QtCore.QSize(750, 530))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        # self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(30, 10, 650, 500))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(12)
        self.tableWidget.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn
        )
        self.tableWidget.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn
        )
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.tableWidget.setColumnWidth(3, 190)
        MainWindow.setCentralWidget(self.centralwidget)

        # for i in range(10):
        #     self.tableWidget.setItem(i, 1, (rankingList[i].getUscore))  # 设置表格项
        #     self.tableWidget.setItem(i, 2, (rankingList[i].getUscore))
        #     self.tableWidget.setItem(i, 3, (rankingList[i].getUtime))

        # self.tableWidget.update()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Rank", "Rank"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Rank", "排名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Rank", "用户"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Rank", "最高分"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Rank", "时间"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)

        i = 0
        rankingList = getRankingList()



        for j in rankingList:
            row_count = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_count)
            item = None
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 0, item)
            self.tableWidget.item(i, 0).setText(_translate("Rank", str(i + 1)))
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 1, item)
            self.tableWidget.item(i, 1).setText(_translate("Rank", j.getUsername()))
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 2, item)
            self.tableWidget.item(i, 2).setText(_translate("Rank", str(j.getUscore())))
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 3, item)
            self.tableWidget.item(i, 3).setText(_translate("Rank", j.getUtime()))
            i += 1

        # item.setText(_translate("MainWindow", str(rankingList[9].getUtime)))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
