# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\VScode__projects\课设\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from src.classes.GameRecord import GameRecord
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget

rankingList = [GameRecord("test1",1000,"2024-06-23 10:52"),GameRecord("test2",800,"2024-06-23 7:52"),GameRecord("test3",100,"2024-06-23 5:52")]
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Rank")
        MainWindow.setEnabled(False)
        MainWindow.resize(700, 530)
        MainWindow.setMinimumSize(QtCore.QSize(750, 530))
        MainWindow.setMaximumSize(QtCore.QSize(750, 530))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(30, 10, 650, 600))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(10)
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 0, item)
        self.tableWidget.setColumnWidth(3,190)
        MainWindow.setCentralWidget(self.centralwidget)
        
       
        # for i in range(10):
        #     self.tableWidget.setItem(i, 1, (rankingList[i].getUscore))  # 设置表格项
        #     self.tableWidget.setItem(i, 2, (rankingList[i].getUscore))
        #     self.tableWidget.setItem(i, 3, (rankingList[i].getUtime))

        #self.tableWidget.update()   


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Rank", "Rank"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Rank", "排名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Rank", "用户"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Rank", "最高分"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Rank", "时间"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Rank", "1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Rank", "2"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Rank", "3"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Rank", "4"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Rank", "5"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Rank", "6"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Rank", "7"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Rank", "8"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Rank", "9"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Rank", "10"))
        i = 0
        for j in rankingList:
            item = None
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 1, item)
            self.tableWidget.item(i,1).setText(_translate("Rank", j.getUsername()))
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 2, item)
            self.tableWidget.item(i,2).setText(_translate("Rank", str(j.getUscore())))
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 3, item)
            self.tableWidget.item(i,3).setText(_translate("Rank", j.getUtime()))
            i+=1
        # item.setText(_translate("MainWindow", str(rankingList[9].getUtime)))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
